import requests

cookies = {
    '_ga': 'GA1.2.167511613.1625830618',
    '_gid': 'GA1.2.1278163209.1626164844',
    'trustedsite_visit': '1',
    'ApplicationGatewayAffinityCORS': '4718ff8aec2f67ac241b685ba359ff88',
    'ApplicationGatewayAffinity': '4718ff8aec2f67ac241b685ba359ff88',
    'ASP.NET_SessionId': 'zyki5cuj5t4vahzfejvobsey',
}

headers = {
    'Connection': 'keep-alive',
    'sec-ch-ua': '" Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"',
    'Accept': '*/*',
    'X-Requested-With': 'XMLHttpRequest',
    'sec-ch-ua-mobile': '?0',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36',
    'Content-Type': 'application/x-www-form-urlencoded; charset=UTF-8',
    'Origin': 'https://v3.lolagrove.com',
    'Sec-Fetch-Site': 'same-origin',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Dest': 'empty',
    'Referer': 'https://v3.lolagrove.com/',
    'Accept-Language': 'en-US,en;q=0.9',
}
def get_form_data_campaign(key,row):
    formdata = [
    ('k', key.replace('"','')),
    ('t', 'json'),
    ('a', 'ud'),
    ('vid', str(row['ID'])),
    ('uid', '1449'),
    ('d[fieldNames][]', 'meritleadid'),
    ('d[fieldNames][]', 'email'),
    ('d[fieldNames][]', 'email_evidence'),
    ('d[fieldNames][]', 'telephone'),
    ('d[fieldNames][]', 'phone_evidence'),
    ('d[fieldNames][]', 'telephone2'),
    ('d[fieldNames][]', 'phone2_evidence'),
    ('d[fieldNames][]', 'address1'),
    ('d[fieldNames][]', 'address2'),
    ('d[fieldNames][]', 'towncity'),
    ('d[fieldNames][]', 'county'),
    ('d[fieldNames][]', 'postcode'),
    ('d[fieldNames][]', 'country'),
    ('d[fieldNames][]', 'address_evidence'),
    ('d[fieldNames][]', 'firstname'),
    ('d[fieldNames][]', 'lastname'),
    ('d[fieldNames][]', 'linkedin_id_url'),
    ('d[fieldNames][]', 'jobtitle'),
    ('d[fieldNames][]', 'jobtitle_evidence'),
    ('d[fieldNames][]', 'job_function'),
    ('d[fieldNames][]', 'companyname'),
    ('d[fieldNames][]', 'company_url'),
    ('d[fieldNames][]', 'industry'),
    ('d[fieldNames][]', 'company_evidence'),
    ('d[fieldNames][]', 'company_size'),
    ('d[fieldNames][]', 'companysize_evidence'),
    ('d[fieldNames][]', 'turnover'),
    ('d[fieldNames][]', 'turnover_evidence'),
    ('d[fieldNames][]', 'supplier_lead_id'),
    ('d[fieldNames][]', 'asset_title'),
    ('d[fieldNames][]', 'comments'),
    ('d[fieldNames][]', 'rejection_evidence'),
    ('d[fieldNames][]', 'useragent'),
    ('d[fieldNames][]', 'lead_creation_date'),
    ('d[fieldNames][]', 'tactic'),
    ('d[fieldNames][]', 'source'),
    ('d[fieldNames][]', 'sub_source'),
    ('d[fieldNames][]', 'update_date'),
    ('d[fieldNames][]', 'switching_to_cloud'),
    ('d[fieldNames][]', 'international_business_payments'),
    ('d[fieldNames][]', 'breach_documents'),
    ('d[fieldNames][]', 'annual_foreign_exchange'),
    ('d[fieldNames][]', 'annual_revenue'),
    ('d[fieldNames][]', 'payment_frequency'),
    ('d[fieldNames][]', 'call_comments'),
    ('d[fieldNames][]', 'input_placement'),
    ('d[fieldNames][]', 'secure'),
    ('d[fieldNames][]', 'lead_type'),
    ('d[fieldNames][]', 'lead_creation_day'),
    ('d[fieldNames][]', 'lead_creation_month'),
    ('d[fieldNames][]', 'lead_creation_year'),
    ('d[fieldNames][]', 'add_notes'),
    ('d[fieldNames][]', 'ds_email'),
    ('d[fieldNames][]', 'sub_id'),
    ('d[fieldNames][]', 'callback_id'),
    ('d[fieldValues][]', row['ID']),
    ('d[fieldValues][]', row['Email']),
    ('d[fieldValues][]', row['email_evidence']),
    ('d[fieldValues][]', row['Telephone']),
    ('d[fieldValues][]', row['phone_evidence']),
    ('d[fieldValues][]', row['telephone2']),
    ('d[fieldValues][]', row['phone2_evidence']),
    ('d[fieldValues][]', row['Address 1']),
    ('d[fieldValues][]', row['Address 2']),
    ('d[fieldValues][]', row['Town/City']),
    ('d[fieldValues][]', row['County/State']),
    ('d[fieldValues][]', row['Postal/Zip Code']),
    ('d[fieldValues][]', row['Country']),
    ('d[fieldValues][]', row['address_evidence']),
    ('d[fieldValues][]', row['First Name']),
    ('d[fieldValues][]', row['Last Name']),
    ('d[fieldValues][]', row['linkedin_id_url']),
    ('d[fieldValues][]', row['Job Title']),
    ('d[fieldValues][]', row['jobtitle_evidence']),
    ('d[fieldValues][]', row['job_function']),
    ('d[fieldValues][]', row['Company Name']),
    ('d[fieldValues][]', row['company_url']),
    ('d[fieldValues][]', row['Industry']),
    ('d[fieldValues][]', row['company_evidence']),
    ('d[fieldValues][]', row['company_size']),
    ('d[fieldValues][]', row['companysize_evidence']),
    ('d[fieldValues][]', row['turnover']),
    ('d[fieldValues][]', row['turnover_evidence']),
    ('d[fieldValues][]', row['Supplier Lead ID']),
    ('d[fieldValues][]', row['asset_title']),
    ('d[fieldValues][]', row['comments']),
    ('d[fieldValues][]', row['rejection_evidence']),
    ('d[fieldValues][]', row['User Agent']),
    ('d[fieldValues][]', row['lead_creation_date']),
    ('d[fieldValues][]', row['tactic']),
    ('d[fieldValues][]', row['Source']),
    ('d[fieldValues][]', row['sub_source']),
    ('d[fieldValues][]', row['update_date']),
    ('d[fieldValues][]', row['switching_to_cloud']),
    ('d[fieldValues][]', row['international_business_payments']),
    ('d[fieldValues][]', row['breach_documents']),
    ('d[fieldValues][]', row['annual_foreign_exchange']),
    ('d[fieldValues][]', row['annual_revenue']),
    ('d[fieldValues][]', row['payment_frequency']),
    ('d[fieldValues][]', row['call_comments']),
    ('d[fieldValues][]', row['input_placement']),
    ('d[fieldValues][]', row['secure']),
    ('d[fieldValues][]', row['lead_type']),
    ('d[fieldValues][]', row['lead_creation_day']),
    ('d[fieldValues][]', row['lead_creation_month']),
    ('d[fieldValues][]', row['lead_creation_year']),
    ('d[fieldValues][]', row['add_notes']),
    ('d[fieldValues][]', row['ds_email']),
    ('d[fieldValues][]', row['Sub_id']),
    ('d[fieldValues][]', row['Callback_id']),
    ('rv', 'false'),
    ]
    return formdata
